apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
data:
  APP_SIZE_OF_FILE_MB: "${APP_SIZE_OF_FILE_MB}"
  APP_SIZE_OF_PVC_GB: "${APP_PVC_SIZE_GB}"
  APP_CHURN_PERCENTAGE: "${APP_CHURN_PERCENTAGE}"
  APP_CHURN_INTERVAL_MINUTES: "${APP_CHURN_INTERVAL_MINUTES}"  