name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iuriikogan/k8sfilechurner:$(date +%s)
    - name: Push the Docker image
      run: docker buildx --platform linux/amd64 --tag iuriikogan/k8sfilechurner:$(date +%s) --push .