name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: 
      - "main" 
    tags:
      - "v*"
  pull_request:

env:
  IMAGE_NAME: k8sfilechurner    

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

      - name: use Docker Buildx
        uses: docker/setup-buildx-action@v1  

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest,v1.${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
